#ifndef SETTINGS_H
#define SETTINGS_H

#define MONOPOLY_NUM_PLAYERS 4
#define MONOPOLY_MOVE_LIMIT 5000
#define MONOPOLY_BOARD_SPACES 10

#define PASS_GO_AMOUNT 200

#define PROPERTY_RENT 200
#define PROPERTY_HOUSE_COST 1000

#define CHANCE_GIVE_PLAYER_MONEY 1000
#define CHANCE_TAKE_PLAYER_MONEY 1001
#define CHANCE_MOVE_BACK_PLAYER 1002
#define CHANCE_MOVE_FORWARD_PLAYER 1003
#define CHANCE_ASSIGN_NEW_INVESTMENT_STRATEGY 1004

#define SPACE_TYPE_GO 2000
#define SPACE_TYPE_PROPERTY 2001
#define SPACE_TYPE_CHANCE 2002

#endif
